//-------------------------------------------------
// Hoverboard
//-------------------------------------------------

const STRIP_SKATES=5000;
const ENC_SKATES=55;
const HDLD_SKATES="HVB";

class DummyBoard:Actor{
    default{
        +nointeraction
    }
    
    states{
    spawn:
     HOVR A 1 A_StartSound("misc/hoverboard");
     HOVR A 1 A_StartSound("misc/hoverboard");
     stop;
    }
}

class WornHoverboard:HDDamageHandler{
	default{
		+nointeraction;
		+noblockmap;
		-hdpickup.fullcoverage
		-inventory.isarmor
		
		inventory.maxamount 1;
		inventory.amount 1;
		HDDamageHandler.priority 0;
		HDPickup.wornlayer STRIP_SKATES;
		HDPickup.overlaypriority 0;
		tag "hoverboard";
	}
	
	states{spawn:TNT1 A 0;stop;}

	override inventory createtossable(int amt){
		let rrr=owner.findinventory("Hoverboard");
		if(rrr)owner.useinventory(rrr);else destroy();
		return null;
	}
	
	override void attachtoowner(actor owner){
		if(!owner.countinv("Hoverboard"))
			owner.A_GiveInventory("Hoverboard");
			
		super.attachtoowner(owner);
	}
	
	override void DetachFromOwner(){
		owner.A_TakeInventory("Hoverboard",1);
		//HDArmour.ArmourChangeEffect(owner,10);
		
		super.DetachFromOwner();
	}
	
	override void DoEffect(){
	//stuff here happens every tic
    	let hp=HDPlayerPawn(owner);
	    let of=owner.friction;
	
	    if(hp){
	        owner.friction=1.08;
	        owner.A_SpawnItemEx(
	        "DummyBoard",
	        0, 4, 0,
	        0, 0, 0,
	        -90
	        );
	    }else{
	        owner.friction=of;
	        }
	    if(!hp){destroy();return;}
	    
	}
	
	override double RestrictSpeed(double speedcap){
	//this changes how fast a player can move while wearing this
	return min(speedcap, 4);//default is 1.8
	}
	
 	override void DrawHudStuff(
		hdstatusbar sb,
		hdplayerpawn hpl,
		int hdflags,
		int gzflags
	){
		bool am=hdflags&HDSB_AUTOMAP;
		sb.drawimage(
			"HOVRA0",
			am?(11,107):(-130,-3),
			am?sb.DI_TOPLEFT:
			(sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_ITEM_CENTER_BOTTOM)
		);
	}
	
}


class Hoverboard:HDPickup{
	default{
		//$Category "Gear/Hideous Destructor/Supplies"
		//$Title "hoverboard"
		//$Sprite "HOVRA0"

		//inventory.pickupmessage "You got the hoverboard!";
		inventory.pickupsound "weapons/pocket";
		inventory.icon "HOVRA0";
		hdpickup.bulk ENC_SKATES;
		tag "$TAG_HOVERBOARD";
		hdpickup.refid HDLD_SKATES;
	}

	override void DetachFromOwner(){
		owner.A_TakeInventory("Hoverboard");
		owner.A_TakeInventory("WornHoverboard");
		target=owner;
		super.DetachFromOwner();
	}

	override inventory CreateTossable(int amt){
		if(
			amount<2
			&&owner.findinventory("WornHoverboard")
		){
			owner.UseInventory(self);
			return null;
		}
		return super.CreateTossable(amt);
	}

	override bool BeforePockets(actor other){
		if(
			other.player
			&&other.player.cmd.buttons&BT_USE
			&&!other.findinventory("WornHoverboard")
		){
			wornlayer=STRIP_SKATES;
			bool intervening=!HDPlayerPawn.CheckStrip(other,self,false);
			wornlayer=0;

			if(intervening)return false;

			//HDArmour.ArmourChangeEffect(other,10);//default is 120
			let onr=HDPlayerPawn(other);

			other.A_GiveInventory("Hoverboard");
			other.A_GiveInventory("WornHoverboard");
			destroy();
			return true;
		}
		return false;
	}
	
	override void DoEffect(){
		bfitsinbackpack=(amount!=1||!owner||!owner.findinventory("WornHoverboard"));
		super.doeffect();
	}
	
	states{
	spawn:
		HOVR A -1;
	use:
		TNT1 A 0{
			let owrs=wornhoverboard(findinventory("WornHoverboard"));
			
			if(owrs){
				if(!HDPlayerPawn.CheckStrip(self,owrs))return;
			}else{
				invoker.wornlayer=STRIP_SKATES+1;
				if(!HDPlayerPawn.CheckStrip(self,invoker)){
					invoker.wornlayer=0;
					return;
				}
				invoker.wornlayer=0;
			}

			//HDArmour.ArmourChangeEffect(self,10);//default is 120
			let onr=HDPlayerPawn(self);
			
			if(!countinv("WornHoverboard")){
				A_GiveInventory("WornHoverboard");
			}else{
				actor a;int b;
				inventory wrs=findinventory("WornHoverboard");
				[b,a]=A_SpawnItemEx("Hoverboard",0,0,height*0.5,0.2,0,2);
				if(a && wrs){
					vel.z+=0.2;
					vel.xy+=(cos(angle),sin(angle))*0.7;
				}
				A_TakeInventory("WornHoverboard");
			}
			player.crouchfactor=min(player.crouchfactor,0.7);
		}fail;
	}
}

class HoverboardSpawn:actor{
	override void postbeginplay(){
		super.postbeginplay();
  		A_SpawnItemEx("Hoverboard",random(-5,5),random(-5,5),flags:SXF_NOCHECKPOSITION);
		self.Destroy();
	}
}